
import os
import requests
import json
import subprocess
import time
import platform
import urllib3

# Strict SSL Verification Enabled
# urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# CONFIGURATION
SERVER_URL = "https://localhost:8443/api/submit-report"
HOSTNAME = platform.node()
INTERVAL = 10 # Seconds for demo (usually slower in prod)
IS_WINDOWS = platform.system() == "Windows"

# Use existing certificates generated by pki_setup.py
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CERT_DIR = os.path.join(BASE_DIR, "certs", "clients", "agent-001")
CA_CERT = os.path.join(BASE_DIR, "certs", "ca", "ca.crt")

CLIENT_CERT = os.path.join(CERT_DIR, "client.crt")
CLIENT_KEY = os.path.join(CERT_DIR, "client.key")

def check_files():
    files = [CLIENT_CERT, CLIENT_KEY, CA_CERT]
    for f in files:
        if not os.path.exists(f):
            print(f"[!] Critical Error: Certificate file not found: {f}")
            print("Did you run 'python pki_setup.py' first?")
            return False
    return True

def run_script(script_name):
    script_path = os.path.join(BASE_DIR, script_name)
    if not os.path.exists(script_path):
        print(f"[!] Script not found: {script_path}")
        return None
        
    try:
        # Run PowerShell script
        result = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", script_path, "-Type", "monitor"],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            # Check if JSON output file path is returned
            output_path = result.stdout.strip()
            if os.path.exists(output_path) and output_path.endswith(".json"):
                with open(output_path, 'r', encoding='utf-16') as f:
                    return json.load(f)
            # Or maybe script returned JSON directly (NetworkMonitor)
            try:
                return json.loads(result.stdout)
            except:
                pass
        return None
    except Exception as e:
        print(f"Error running {script_name}: {e}")
        return None

def gather_audit():
    """OS-aware audit: PowerShell Auditor on Windows, native Linux auditor on Linux."""
    if IS_WINDOWS:
        return run_script("Auditor.ps1")
    # Linux (and other POSIX): use the bundled Python auditor.
    try:
        from linux_auditor import LinuxAuditor
        return LinuxAuditor().audit()
    except Exception as e:
        print(f"[!] Linux audit failed: {e}")
        return None


def main():
    if not check_files(): return
    print(f"[*] Starting Host Monitor for {HOSTNAME} ({platform.system()})")
    print(f"[*] Target Server: {SERVER_URL}")

    while True:
        # 1. Run and Send Audit
        print("Gathering System Audit Data...", end="", flush=True)
        audit_data = gather_audit()
        if audit_data:
            audit_data['Hostname'] = HOSTNAME
            try:
                res = requests.post(
                    SERVER_URL, 
                    json=audit_data,
                    cert=(CLIENT_CERT, CLIENT_KEY),
                    verify=CA_CERT 
                )
                if res.status_code == 200:
                    print(" [Sent]")
                    try:
                        resp_data = res.json()
                        cmd = resp_data.get('command', 'none')
                        targets = resp_data.get('targets', [])

                        if cmd == 'remediate' and not IS_WINDOWS:
                            # Automated Linux remediation is not wired yet; the exact fix
                            # commands are shown per-finding in the dashboard.
                            print(f"[!] Server requested remediation. Targets: {targets or 'ALL'}")
                            print("[i] Linux remediation is manual for now - see remediation commands in the dashboard.")
                        elif cmd == 'remediate':
                            print(f"[!] Server requested remediation. Targets: {targets or 'ALL'}")
                            h_path = os.path.join(BASE_DIR, "Hardener.ps1")

                            if os.path.exists(h_path):
                                # Build command dynamically
                                ps_cmd = ["powershell", "-ExecutionPolicy", "Bypass", "-File", h_path]
                                if targets and isinstance(targets, list) and len(targets) > 0:
                                     # Pass targets as comma-separated string for PowerShell array
                                     target_str = ",".join(targets)
                                     ps_cmd.extend(["-Targets", target_str])
                                
                                print(f"[*] Running: {' '.join(ps_cmd)}")
                                h_res = subprocess.run(
                                    ps_cmd, 
                                    capture_output=True, 
                                    text=True
                                )
                                if h_res.returncode == 0:
                                    print("[*] Hardening Success:\n" + h_res.stdout)
                                else:
                                    print("[!] Hardening FAILED:\n" + h_res.stderr + "\n" + h_res.stdout)
                            else:
                                print(f"[!] ERR: Hardener.ps1 not found at {h_path}")
                    except Exception as e:
                        print(f" [Cmd Error: {e}]")
                else: print(f" [Failed: {res.status_code}]")
            except Exception as e: 
                print(f" [Error: {e}]")
        else: print(" [Skipped]")

        # 2. Run and Send Network Data (Windows agent only for now)
        if not IS_WINDOWS:
            time.sleep(INTERVAL)
            continue
        print("Gathering Network Connections...", end="", flush=True)
        net_data = run_script("NetworkMonitor.ps1")
        if net_data:
            payload = {"Hostname": HOSTNAME, "Connections": net_data}
            try:
                res = requests.post(
                    "https://localhost:8443/api/network-traffic", 
                    json=payload,
                    cert=(CLIENT_CERT, CLIENT_KEY),
                    verify=CA_CERT 
                )
                if res.status_code == 200: print(" [Sent]")
                else: print(f" [Failed: {res.status_code}]")
            except: print(" [Error]")
        else: print(" [Skipped]")

        time.sleep(INTERVAL)

if __name__ == "__main__":
    main()
